In [3]:
import Stresess3D_functions as S3DF
import sympy as sp
import numpy as np


In [4]:
#1 EXAMPLE STRESSES TRANFORMATION

T_ij = np.array([[ 60, 40, -40],
                 [ 40, 0,  -20],
                 [-40, -20, 20]])


l1 = sp.cos(sp.rad(30)).evalf()
m1 = sp.cos(sp.rad(60)).evalf()
n1 = sp.cos(sp.rad(90)).evalf()
l2 = sp.cos(sp.rad(120)).evalf()
m2 = sp.cos(sp.rad(30)).evalf()
n2 = sp.cos(sp.rad(90)).evalf()
l3 = sp.cos(sp.rad(90)).evalf()
m3 = sp.cos(sp.rad(90)).evalf()
n3 = sp.cos(sp.rad(0)).evalf()

T = np.array([[l1,m1,n1],
              [l2,m2,n2],
              [l3,m3,n3]])

T_ij_prime = S3DF.transform_stress_tensor(T_ij, T)
display(T_ij_prime)

x'stresses are:


array([79.6410161513775, -5.98076211353316, -44.6410161513775],
      dtype=object)

y'stresses are:


array([-5.98076211353316, -19.6410161513775, 2.67949192431123],
      dtype=object)

z'stresses are:


array([-44.6410161513775, 2.67949192431123, 20.0000000000000],
      dtype=object)

array([[79.6410161513775, -5.98076211353316, -44.6410161513775],
       [-5.98076211353316, -19.6410161513775, 2.67949192431123],
       [-44.6410161513775, 2.67949192431123, 20.0000000000000]],
      dtype=object)

In [5]:
#2 EXAMPLE INVARIANTS COMPUTATION
T_ij_1 = np.array([[ 60, 40, -40],
                 [ 40, 0,  -20],
                 [-40, -20, 20]])
invariants_1 = S3DF.get_stress_invariant(T_ij_1)

I1:


80

I2:


-2400

I3:


7999.999999999986

In [6]:
#3 EXAMPLE PRINCIPAL STRESSES COMPUTATION

I = [26,-349,-6464]
S3DF.get_principal_stresses(I)

26 -349 -6464


array([-16.9785768 ,  30.49342351,  12.48515329])

In [7]:
#4 EXAMPLE PRINCIPAL DIRECTIONS COMPUTATION
T_ij = np.array([[30, 0, 20],
                 [0, 0, 0],
                 [20, 0, 0]])
S1 = -10

S3DF.get_principal_directions(T_ij,S1)

El espacio nulo (soluciones) es:
[[ 0.4472136 ]
 [ 0.        ]
 [-0.89442719]]
