In [1]:
import numpy as np
import sympy as sp

def transform_strain_tensor(strain_tensor, direction_cosines):
    """
    Transform a strain tensor given in certain reference system to other strain tensor, 
    in other system of reference given for direction cosines.

    Parameters
    ----------
    -  strain_tensor(np.array) : array with the original strain tensor
    -  direction_cosines(np.array) : array with the direction cosines which describe de position 
                                            of the new coordinate system regarding the original cosine system 
                                            defined as the text book

    Returns
    -------
     - transformed_strain_tensor(np.array) : stress tensor in the new coordinate system
    """
    # Extract rows as vectors
    l1_m1_n1 = direction_cosines[0, :].T  # First row
    l2_m2_n2 = direction_cosines[1, :].T  # Second row
    l3_m3_n3 = direction_cosines[2, :].T  # Third row
    
    x_prime_plane_strains = direction_cosines @ strain_tensor @  l1_m1_n1 
    y_prime_plane_strains = direction_cosines @ strain_tensor @  l2_m2_n2 
    z_prime_plane_strains = direction_cosines @ strain_tensor @  l3_m3_n3 
    print("x'strains are:")
    display( x_prime_plane_strains)
    print("y'strains are:")
    display( y_prime_plane_strains)
    print("z'strains are:")
    display( z_prime_plane_strains)
    
    Ex_prime  = x_prime_plane_strains[0]
    O5_Gxy_prime = x_prime_plane_strains[1]
    O5_Gxz_prime = x_prime_plane_strains[2]
    Ey_prime  = y_prime_plane_strains[1]
    O5_Gyz_prime = y_prime_plane_strains[2]
    Ez_prime  = z_prime_plane_strains[2]
  
    

    transformed_strain_tensor = np.array([[Ex_prime, O5_Gxy_prime, O5_Gxz_prime],
                                           [O5_Gxy_prime, Ey_prime, O5_Gyz_prime],
                                           [O5_Gxz_prime, O5_Gyz_prime, Ez_prime]])
 
    return transformed_strain_tensor


In [3]:

E_ij = (10**-6)*np.array([[ 200, 300, 200],
                          [ 300, -100,  500],
                          [200, 500, -400]]) 


l1 = 0.86
m1 = 0.5
n1 = 0
l2 = 0
m2 = 0
n2 = 0
l3 = 0
m3 = 0
n3 = 0

T = np.array([[l1,m1,n1],
              [l2,m2,n2],
              [l3,m3,n3]])

E_ij_prime = transform_strain_tensor(E_ij, T)
np.set_printoptions(suppress=False, precision=3, formatter={'float': '{:0.3e}'.format})
display(E_ij_prime)

x'strains are:


array([0.00038092, 0.        , 0.        ])

y'strains are:


array([0., 0., 0.])

z'strains are:


array([0., 0., 0.])

array([[3.809e-04, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00]])