In [2]:
import Strains3D_functions as E3DF
import sympy as sp
import numpy as np

In [3]:
# 1 EXAMPLE:  STRAINS TRANSFORMATION 

E_ij = (10**-6)*np.array([[ 200, 300, 200],
                          [ 300, -100,  500],
                          [200, 500, -400]]) 

l1 = 0.86
m1 = 0.5
n1 = 0
l2 = 0
m2 = 0
n2 = 0
l3 = 0
m3 = 0
n3 = 0

T = np.array([[l1,m1,n1],
              [l2,m2,n2],
              [l3,m3,n3]])

E_ij_prime = E3DF.transform_strain_tensor(E_ij, T)
np.set_printoptions(suppress=False, precision=3, formatter={'float': '{:0.3e}'.format})
display(E_ij_prime)

x'strains are:


array([0.00038092, 0.        , 0.        ])

y'strains are:


array([0., 0., 0.])

z'strains are:


array([0., 0., 0.])

array([[3.809e-04, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00]])

In [4]:
#3 EXAMPLE : STRAIN INVARIANTS
E_ij = (10**-6)*np.array([[ 200, 300, 200],
                          [ 300, -100,  500],
                          [200, 500, -400]]) 

invariants = E3DF.get_strain_invariants(E_ij)
np.set_printoptions(suppress=False, precision=3, formatter={'float': '{:0.3e}'.format})
display(invariants)

I1:


-0.0003

I2:


-4.3999999999999997e-07

I3:


5.799999999999999e-11

[-0.0003, -4.3999999999999997e-07, 5.799999999999999e-11]

In [5]:
#3 EXAMPLE: PRINCIPAL STRAINS
I = [-0.0003, -4.3999999999999997e-07, 5.799999999999999e-11]
np.set_printoptions(suppress=False, precision=3, formatter={'float': '{:0.3e}'.format})
E3DF.get_principal_strains(I)

-0.0003 -4.3999999999999997e-07 5.799999999999999e-11


array([-7.724e-04, 5.980e-04, -1.256e-04])

In [6]:
#4 EXAMPLE: GETTING STRAIN FROM STRES TENSOR

T_ij = (10**-6)*np.array([[ 20, -4, 5],
                          [ -4, 0,  10],
                          [5, 10, 15]])
np.set_printoptions(suppress=False, precision=3, formatter={'float': '{:0.3e}'.format})
E3DF.get_strains_from_stresses(T_ij,(200*10**3),(800*10**3),0.25)

array([[8.125e-11, -2.500e-12, 3.125e-12],
       [-2.500e-12, -4.375e-11, 6.250e-12],
       [3.125e-12, 6.250e-12, 5.000e-11]])